### ISSUE TITLE
Generation hangs at 50% perpetually

### ISSUE THREAD

**Issue by muffinjets** [TheBetaM/CrateModLoader#11]
I was able to generate a Crash 2 game about a year ago, but ever since then I've attempted to do a new one a few times with generation stopping at 50%, no matter what.  I don't know any context of why this would work this way, only that it reliably happens with both Crash 2 and Warped.

**Comment by Spatulade** [comment]
I'm pretty sure it's "Randomize World Textures" that causes the issue, turn it off and it should work.
